### ISSUE TITLE
Sometimes inverts or is missing parts

### ISSUE THREAD

**Issue by Henry00IS** [nickgravelyn/Triangulator#1]
**Edit: I am truly sorry in case this turns out to be my own fault...**

Hey, I started using your amazing project inside of [SabreCSG](https://github.com/sabresaurus/SabreCSG) to build a 2D Shape Editor (that lets you extrude any shape to a 3D Brush). Now for a lot of shapes I often get these missing parts, is that just part of the algorithm or is there any way to fix it?

These polygons are missing in the center (EDIT: OR IT'S INVERTED! Where the empty space is the output):

![image](https://user-images.githubusercontent.com/7905726/36206323-40df5368-1192-11e8-9641-0ba1b16f3127.png)

There are way more difficult shapes that it's able to handle perfectly:

![image](https://user-images.githubusercontent.com/7905726/36206399-8b62ce56-1192-11e8-8fec-8c817bbfef4d.png)
![image](https://user-images.githubusercontent.com/7905726/36208207-9a8337ee-1198-11e8-8461-9b419fc86ba7.png)

There are more weird issues where moving another polygon inside causes all the output to invert:
And moving it to the right actually fixes the center.

![image](https://user-images.githubusercontent.com/7905726/36207325-c2d89cf0-1195-11e8-887c-e20ee4ac87df.png)

Any help or advice would be very much appreciated! :)

*Edit: Several edits occurred, but this is not my fault AFAIK.*

**Comment by Henry00IS** [comment]
Alright I figured out the problem. For some reason the winding order detection in Triangulator.Triangulate() gets confused. Since I guarantee my winding order to be clockwise I left only this one line intact to make it work in all of the cases above:

![image](https://user-images.githubusercontent.com/7905726/36213231-7c99b074-11a6-11e8-982a-eeaed08a86ea.png)

**Comment by nickgravelyn** [comment]
Yeah that definitely looks like a failure to automatically detect the winding order. It's been ages since I've been in the code so I have no idea what the "real" fix would be but I'm glad you were able to make it work for you. :)

I'm going to close this since I'm not really working on this library; I simply uploaded it here from Codeplex when Microsoft was shutting that down.
